version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
    - master
environment:
    my_encrypted_sonarqube_token:
        secure: auSP7uJIC8Y5I0AW97f0ANIOLXxkszux38+nFJhry4PFvH1MBd1xfBFMcA30a8Z9
install:
    - choco install "sonarscanner-msbuild-netcoreapp2.0" -y

before_build:
    - cmd: nuget restore Src/BlazingPoints.sln
    - choco install opencover.portable
    - choco install codecov
    - dotnet tool install -g dotnet-sonarscanner
    - dotnet sonarscanner begin /key:"GregTrevellick_AzureDevOpsBlazorRadiator" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%my_encrypted_sonarqube_token%" /o:"gregtrevellick-github"
build:
    project: Src/BlazingPoints.sln
    verbosity: minimal
after_build:
    - dotnet sonarscanner end /d:"sonar.login=%my_encrypted_sonarqube_token%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
