version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
    - master
environment:
    my_encrypted_sonarqube_token:
        secure: 94Py9ytqrmqFVtmUiyayJJ4Hgg2vjF1+YuRJldGGWO82/9zEens+sCjeh7wzc2Le
install:
    - choco install "sonarscanner-msbuild-netcoreapp2.0" -y
    - nuget sources add -Name MyDevExpress -Source https://nuget.devexpress.com/%nuget_password%/api -UserName %nuget_user% -Password %nuget_password%

before_build:
    - cmd: nuget restore Src/BlazingPoints.sln
    - choco install opencover.portable
    - choco install codecov
    - SonarScanner.MSBuild.exe begin /k:"BlazingPoints" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%my_encrypted_sonarqube_token%" /d:"sonar.organization=gregtrevellick-github"
build:
    project: Src/BlazingPoints.sln
    verbosity: minimal
after_build:
    - SonarScanner.MSBuild.exe end /d:"sonar.login=%my_encrypted_sonarqube_token%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
